# Generated by Django 4.1.3 on 2022-11-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_watchlist_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='category_id',
            new_name='category',
        ),
    ]
